### ISSUE TITLE
AutoDL 模型下载错误

### ISSUE THREAD

**Issue by koking0** [tzwm/autodl-sd-webui#8]
尝试下载以下两个模型：
- https://civitai.com/models/89804/ip-design-or-3d
- https://civitai.com/models/263287

都是显示错误：
![image](https://github.com/tzwm/sd-scripts/assets/45281765/239f2eae-7ad0-44c1-a189-573d843fcc6c)

报错日志：
```
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py", line 109, in preview
    return [f"预览成功{more_guides}"] + resp_to_components(resp) + \
  File "/root/stable-diffusion-webui/extensions/sd-webui-model-downloader-cn/scripts/model-downloader-cn.py", line 89, in resp_to_components
    resp["version"]["updatedAt"],
KeyError: 'updatedAt'
```

**Comment by Pangu-Immortal** [comment]
C站需要梯子才能访问，配置好clash就行了。但是该如何配置呢？貌似这个包里的不能用。
这个是安装包：https://github.com/VocabVictor/clash-for-AutoDL
